### ISSUE TITLE
Feat: DetailPage

### ISSUE THREAD

**Issue by swon95** [group7temp/7-1-#10]
##  📌 기능
-   Detail page implementation
![image](https://github.com/group7temp/7-1-/assets/96659041/0b4a966c-9f3f-4392-8f79-66620720239c)

## 🪴 TODO
- [x] Feat: detail connected route
- [x] Feat: detail api
- [x] Feat: detail components
- [x] Feat: utills function
- [ ] Style: layout
