### ISSUE TITLE
Feat: Search Bar

### ISSUE THREAD

**Issue by cuconveniencestore** [group7temp/7-1-#16]
##  📌 기능
-   Header 내 영상 검색 기능이 있는 검색바 기능
<img width="840" alt="image" src="https://github.com/group7temp/7-1-/assets/125563995/9b90c726-c01e-48a1-87e1-237a0d420c08">
- key 오류 수정  
<img width="840" alt="image" src="https://github.com/group7temp/7-1-/assets/125563995/8dfb22fc-4666-4c96-935e-3cafb37dbf8d">

## 🪴 TODO
- [x] Search Bar component 생성
- [x] Search 검색 결과로 데이터 필터링
- [x] Search Bar design
- [x] 뒤로가기 후 다시 돌아왔을때 검색 내역 저장 기능
- [x] 반응형 스타일 수정
- [x] 상세설명 더보기 기능 추가
- [x] 문자열 상수화
