### ISSUE TITLE
Fix: Detail page 관련 수정

### ISSUE THREAD

**Issue by cuconveniencestore** [group7temp/7-1-#23]
##  📌 기능
- Detail page 관련 수정 사항
<img width="682" alt="image" src="https://github.com/group7temp/7-1-/assets/125563995/ba4bca63-baf6-4e16-bd58-d5a0364fc056">

## 🪴 TODO
- [x] 관련영상 리스트 중복 영상 제외
- [x] 검색창에서 진입 했을 경우 search bar 검색어 출력
- [x] main page에서 뒤로가기(headerBtn) 클릭시 뒤로가기 비활성
