### ISSUE TITLE
Feat: MainPage

### ISSUE THREAD

**Issue by cuconveniencestore** [group7temp/7-1-#3]
##  📌 기능
-  youtube 메인페이지 비디오 컴포넌트를 제외한 레이아웃 및 페이지 로직 설정
<img width="555" alt="image" src="https://github.com/group7temp/7-1-/assets/125563995/22504e5a-5de1-4ec3-a65b-d8484143e728">

## 🪴 TODO
- [ ] Feat: Header 생성
- [ ] Feat: MainPage server 컴포넌트 생성
- [ ] Feat: MainPage client 컴포넌트 생성
- [ ] Design: 비디오 컴포넌트 제외한 레이아웃 구성
