### ISSUE TITLE
Feat: errorPage

### ISSUE THREAD

**Issue by cuconveniencestore** [group7temp/7-1-#30]
##  📌 기능
-   error page 생성 및 적용

## 🪴 TODO
- [ ] error page component 생성
- [ ] error page 뒤로가기 추가
- [ ] error page 연결

## 💡 참고 자료
![image](https://github.com/group7temp/7-1-/assets/125563995/e91ce24b-0564-404b-8288-1b1ce3bb9303)
