### ISSUE TITLE
Feat: MainPage - VideoItem

### ISSUE THREAD

**Issue by swon95** [group7temp/7-1-#4]
##  📌 기능
-   youtube API 더미데이터 활용 -> VideoItem List render

![image](https://github.com/group7temp/7-1-/assets/96659041/50df96f6-99ea-423e-bcf0-135f8a19593f)

## 🪴 TODO
- [ ] feat: client componencts - VideoItem
- [ ] feat: clinet componencts - merge VideoItem into MainPage
- [ ] feat: server components - dataFetch
- [ ] feat: types - TypeListItem, TypeVideoListResponse

## 💡 참고 자료
<https://console.cloud.google.com/apis/dashboard?hl=ko>
